import { Public_Sans } from 'next/font/google'

import Providers from './providers'
import Nav from '@/components/Nav'
import './globals.css'

const publicSans = Public_Sans({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={publicSans.className}>
                <Providers>
                    <main className="main-content">{children}</main>
                    <Nav />
                </Providers>
            </body>
        </html>
    )
}
