import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import Providers from '@/context/Providers';
import MessageList from '@/components/MessageList';
import '@/styles/globals.css';
import styles from './layout.module.css';

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Providers>
                <body className={montserrat.variable}>
                    <section className={styles.navWrapper}>
                        <MessageList />
                    </section>
                    <section className={styles.mainWrapper}>{children}</section>
                    <section className={styles.footerWrapper}></section>
                </body>
            </Providers>
        </html>
    );
}
